# Generated by Django 6.1.1 on 2026-09-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(help_text='e.g. Navratri, Diwali, wedding', max_length=100)),
                ('brief', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('review', 'Awaiting approval'), ('done', 'Done')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pattern_type', models.CharField(choices=[('leheriya', 'Leheriya'), ('ekdali', 'Ekdali'), ('chaubasi', 'Chaubasi'), ('shikari', 'Shikari'), ('other', 'Other')], max_length=20)),
                ('colors', models.CharField(help_text='Comma-separated', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='generations/')),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed_qc', 'Failed QC'), ('passed_qc', 'Passed QC'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('qc_score', models.FloatField(blank=True, null=True)),
                ('qc_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='studio.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.CharField(help_text='1:1, 4:5, 9:16', max_length=10)),
                ('image', models.ImageField(upload_to='ads/')),
                ('caption', models.TextField(blank=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.generation')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='studio.product'),
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('kind', models.CharField(choices=[('flatlay', 'Flat-lay'), ('detail', 'Fabric close-up')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studio.product')),
            ],
        ),
    ]
